apiVersion: fn.kpt.dev/v1alpha1
kind: SetAnnotations
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-fn/set-annotations:v0.1.4
annotations:
  color: orange
  fruit: apple